LoyaltyProgram/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LoyaltyProgram.ViewModels
{
    public class LoginViewModel
    {
        public String Email { get; set; }
        public String Password { get; set; }
        public String CPassword { get; set; }
    }
}

LoyaltyProgram/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoyaltyProgram.ViewModels;
using LoyaltyProgram.Models;
using LoyaltyProgram.DAL;
using System.Data.Entity;

namespace LoyaltyProgram.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private LoyaltyProgramContext db = new LoyaltyProgramContext();

        public ActionResult Index()
        {
            return View();
        }
        // Check for Login
        public ActionResult Login(string email, string password)
        {
            String message = "";
            Customer customer = new Customer();
            User user = new User();
            CustomerViewModel cvm = new CustomerViewModel();
            try
            {
                // 
                customer = db.Customers.Where(_ => _.CustomerEmail == email && _.IsActive == true).FirstOrDefault();
                if (customer != null && customer.CustomerId > 0)
                {
                    if (customer.CustomerPassword != password)
                    {
                        message = "Enter Correct Password";
                    }
                    else
                    {
                        customer.IsLoggedIn = true;
                        db.Entry(customer).State = EntityState.Modified;
                        db.SaveChanges();

                        // Session of type customer view model.
                        cvm.CustomerId = customer.CustomerId;
                        cvm.CustomerFirstName = customer.CustomerFirstName;
                        cvm.CustomerLastName = customer.CustomerLastName;
                        cvm.CustomerEmail = customer.CustomerEmail;
                        cvm.CustomerDOB = customer.CustomerDOB;
                        cvm.CustomerGender = customer.CustomerGender;
                        cvm.CustomerLoyaltyPoints = customer.CustomerLoyaltyPoints;
                        cvm.CustomerLevelId = customer.LevelId;
                        cvm.RoleId = customer.RoleId;
                        cvm.CustomerAddress = customer.CustomerAddress;
                        cvm.CustomerCity = customer.CustomerCity;
                        cvm.CustomerProvince = customer.CustomerProvince;
                        cvm.IsLoggedIn = customer.IsLoggedIn;
                        cvm.CustomerCardNo = customer.CustomerCardNo;
                        cvm.CustomerPhoneNumber = customer.CustomerPhoneNumber;
                        cvm.CustomerPostalCode = customer.CustomerPostalCode;
                        // Creating customer session
                        Session["Customer"] = cvm;
                    }

                }
                else
                {
                    user = db.Users.Where(_ => _.UserEmail == email && _.IsActive == true).FirstOrDefault();
                    if (user != null && user.UserId > 0)
                    {
                        if (user.UserPassword != password)
                        {
                            message = "Enter correct password";
                        }
                        else
                        {
                            user.isLoggedIn = true;
                            db.Entry(user).State = EntityState.Modified;
                            db.SaveChanges();

                            // User Session
                            Session["User"] = user;
                        }
                    }
                    else
                    {
                        message = "Invalid Email ID";
                    }

                }
                return Json(message, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                return Json("", JsonRequestBehavior.AllowGet);
            }


        }
        // Sign out from account
        public ActionResult SignOut()
        {
            CustomerViewModel cvm = new CustomerViewModel();
            Customer c = new Customer();
            User u = new User();
            try
            {
                if (Session["Customer"] != null)
                {
                    cvm = (CustomerViewModel)Session["Customer"];
                    if (cvm != null)
                    {
                        c = db.Customers.Where(_ => _.IsLoggedIn == true && _.CustomerEmail == cvm.CustomerEmail).FirstOrDefault();
                        c.IsLoggedIn = false;
                        db.Entry(c).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                    Session["Customer"] = null;

                }
                else
                {
                    if (Session["User"] != null)
                    {
                        u = (User)Session["User"];
                        if (u != null && u.UserId > 0)
                        {
                            u = db.Users.Where(_ => _.isLoggedIn == true && _.UserEmail == u.UserEmail).FirstOrDefault();
                            u.isLoggedIn = false;
                            db.Entry(u).State = EntityState.Modified;
                            db.SaveChanges();

                        }
                        Session["User"] = null;
                    }
                }
            }
            catch (Exception ex)
            {


            }

            return RedirectToAction("Index");
        }
    }
}

LoyaltyProgram/Controllers/SignupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LoyaltyProgram.DAL;
using LoyaltyProgram.ViewModels;
using LoyaltyProgram.Models;
using System.Configuration;
using System.IO;
using System.Net.Mail;
using System.Net;

namespace LoyaltyProgram.Controllers
{
    public class SignupController : Controller
    {
        // GET: Signup
        private LoyaltyProgramContext db = new LoyaltyProgramContext();
        public ActionResult Index()
        {
            return View();
        }
        // Create Customer
        [HttpPost]
        public ActionResult CreateCustomer(CustomerViewModel customerViewModel)
        {
            try
            {
                if (customerViewModel != null)
                {
                    Customer customer = new Customer();
                    customer.CustomerFirstName = customerViewModel.CustomerFirstName;
                    customer.CustomerLastName = customerViewModel.CustomerLastName;
                    customer.CustomerGender = customerViewModel.CustomerGender;
                    customer.CustomerDOB = customerViewModel.CustomerDOB;
                    customer.CustomerAddress = customerViewModel.CustomerAddress;
                    customer.CustomerCity = customerViewModel.CustomerCity;
                    customer.CustomerProvince = customerViewModel.CustomerProvince;
                    customer.CustomerPostalCode = customerViewModel.CustomerPostalCode;
                    customer.CustomerCardNo = customerViewModel.CustomerCardNo;
                    customer.CustomerPassword = customerViewModel.CustomerPassword;
                    customer.CustomerEmail = customerViewModel.CustomerEmail;
                    customer.CustomerPhoneNumber = customerViewModel.CustomerPhoneNumber;
                    customer.RoleId = getRoleIdForCustomerRole();
                    customer.CreatedOn = DateTime.Now;
                    customer.CustomerLoyaltyPoints = 10000;
                    customer.LevelId = getCustomerLevelId(customerViewModel.CustomerLoyaltyPoints);
                    customer.IsActive = true;
                    db.Customers.Add(customer);
                    db.SaveChanges();
                    sendMail(customerViewModel.CustomerEmail);
                    return RedirectToAction("Index", "Login");

                }

            }
            catch (Exception ex)
            {


            }
            return View("Index");
        }

        // Get RoleId For Customer Role
        public int getRoleIdForCustomerRole()
        {
            Roles role = new Roles();
            try
            {
                role = db.Roles.Where(_ => _.RoleName.Equals("Customer", StringComparison.OrdinalIgnoreCase)).FirstOrDefault();
                return role.RoleId;
            }
            catch (Exception ex)
            {
                return 0;
                //ex.StackTrace.ToString();
            }



        }
        // Get Customer Level  by Points
        public int getCustomerLevelId(double points)
        {
            int levelId = 0;
            List<CustomerLevel> customerLevels = new List<CustomerLevel>();
            try
            {
                customerLevels = db.CustomerLevels.ToList();
                foreach (CustomerLevel clevel in customerLevels)
                {
                    if (points >= clevel.PointsRangeFrom && points <= clevel.PointsRangeTo)
                    {
                        levelId = clevel.LevelId;
                        break;
                    }
                }
                return levelId;
            }
            catch (Exception)
            {

                return levelId;
            }


        }
        // Send Mail on successful Sign Up
        public void sendMail(String username)
        {
            try
            {
                string emailSender = ConfigurationManager.AppSettings["emailsender"].ToString();
                string emailSenderPassword = ConfigurationManager.AppSettings["password"].ToString();
                string emailSenderHost = ConfigurationManager.AppSettings["smtp"].ToString();
                int emailSenderPort = Convert.ToInt16(ConfigurationManager.AppSettings["portnumber"]);
                Boolean emailIsSSL = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSSL"]);
                //string filePath = "~/Templates/SignUpMail.html";
                string path = Server.MapPath("~/Templates/SignUpMail.html");

                StreamReader str = new StreamReader(path);
                string MailText = str.ReadToEnd();
                str.Close();

                //Repalce [newusername] = signup user name   
                MailText = MailText.Replace("[newusername]", username);


                string subject = "Welcome to Loyalty Program";
                MailMessage _mailmsg = new MailMessage();

                //Make TRUE because our body text is html  
                _mailmsg.IsBodyHtml = true;

                //Set From Email ID  
                _mailmsg.From = new MailAddress(emailSender);

                //Set To Email ID  
                _mailmsg.To.Add(username);

                //Set Subject  
                _mailmsg.Subject = subject;

                //Set Body Text of Email   
                _mailmsg.Body = MailText;


                //Now set your SMTP   
                SmtpClient _smtp = new SmtpClient();

                //Set HOST server SMTP detail  
                _smtp.Host = emailSenderHost;

                //Set PORT number of SMTP  
                _smtp.Port = emailSenderPort;

                //Set SSL --> True / False  
                _smtp.EnableSsl = emailIsSSL;

                //Set Sender UserEmailID, Password  
                NetworkCredential _network = new NetworkCredential(emailSender, emailSenderPassword);
                _smtp.Credentials = _network;

                //Send Method will send your MailMessage create above.  
                _smtp.Send(_mailmsg);
            }
            catch (Exception ex)
            {


            }
        }

        // Check for customer email id
        public ActionResult checkMail(string email)
        {
            string message = "";
            try
            {

                Customer customer = new Customer();
                customer = db.Customers.Where(_ => _.CustomerEmail == email).FirstOrDefault();
                if (customer != null && customer.CustomerId > 0)
                {
                    message = "Email Id already exists";
                }

            }
            catch (Exception)
            {

                //return message;
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }
    }
}

LoyaltyProgram/Views/Login/Index.cshtml
@model LoyaltyProgram.ViewModels.LoginViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}
<style>
    .mb-1, .my-1 {
        margin-bottom: .25rem !important;
        margin-top: .25rem;
    }
</style>
<div class="login-box">
    <div class="login-logo">
        Loyalty Program
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Login<p>
                @using (Html.BeginForm("Login", "Login", FormMethod.Post, new { id = "loginForm" }))
                {


                    <div class="input-group mb-3">
                        @Html.Kendo().TextBoxFor(_ => _.Email).HtmlAttributes(new { placeholder = "e.g. myname@example.net", required = "required", type = "email", data_email_msg = "Email format is not valid", @class = "form-control" })

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-envelope"></span>
                            </div>
                        </div>
                        <span class="k-invalid-msg" data-for="Email"></span>
                    </div>
                    <div class="input-group mb-3">
                        @Html.Kendo().TextBoxFor(_ => _.Password).HtmlAttributes(new { placeholder = "Enter Password", required = "required", type = "password", validationmessage = "Enter Password", @class = "form-control" })

                        <div class="input-group-append">
                            <div class="input-group-text">
                                <span class="fas fa-lock"></span>
                            </div>
                        </div>
                        <span class="k-invalid-msg" data-for="Password"></span>
                    </div>
                    <div class="row">

                        <!-- /.col -->
                        <div class="col-4">
                            <button id="btnLogin" type="submit" class="btn btn-primary btn-block">Sign In</button>
                        </div>
                        <!-- /.col -->
                    </div>
                }

            <p class="mb-1">
                @Html.ActionLink("Forgot Password?", "Index", "ForgetPassword", null, null)
                @Html.ActionLink("Sign Up", "Index", "Signup", null, new { style = "float: right;" })
            </p>
            @*<p class="mb-0">

                </p>*@
        </div>
        <!-- /.login-card-body -->
    </div>

</div>
<script>


    $(document).ready(function () {
        var validator = $("form").kendoValidator().data("kendoValidator");
        var status = $(".status");

    });

    $("#loginForm").submit(function (e) {

        var email = $("#Email").val();
        var password = $("#Password").val();
        e.preventDefault(); // avoid to execute the actual submit of the form.

        var form = $(this);
        $.ajax({
            url: "/Login/Login",
            data: { email: email, password: password },
            type: "POST",
            success: function (data) {
                
                if (password != "" && email != "") {
                    if (data != "") {
                        $("#Password").next().show();
                        $("#Password").next().addClass("k-widget k-tooltip k-tooltip-validation k-invalid-msg field-validation-error");
                        $("#Password").next().text(data);
                    }
                    else {
                        window.location.href = '/Home/Index';
                    }

                }



            }
        });

    });
</script>