LoyaltyProgram/ViewModels/ContactUsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LoyaltyProgram.ViewModels
{
    public class ContactUsViewModel
    {
        public String CustomerEmail { get; set; }
        public String CustomerFirstName { get; set; }

        public String CustomerLastName { get; set; }
        public String CustomerPhoneNumber { get; set; }
        public String CustomerCardNo { get; set; }

        public String Comment { get; set; }
    }
}

LoyaltyProgram/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using LoyaltyProgram.ViewModels;

namespace LoyaltyProgram.Controllers
{
    public class ContactUsController : Controller
    {
        // GET: ContactUs
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult sendMail(ContactUsViewModel contactusViewModel)
        {
            sendMailToCompany(contactusViewModel);

            sendMailToCustomer(contactusViewModel);


            return RedirectToAction("Index");
        }
        private void sendMailToCustomer(ContactUsViewModel c)
        {
            try
            {

                string emailSender = ConfigurationManager.AppSettings["emailsender"].ToString();
                string emailSenderPassword = ConfigurationManager.AppSettings["password"].ToString();
                string emailSenderHost = ConfigurationManager.AppSettings["smtp"].ToString();
                int emailSenderPort = Convert.ToInt16(ConfigurationManager.AppSettings["portnumber"]);
                Boolean emailIsSSL = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSSL"]);
                //string filePath = "~/Templates/SignUpMail.html";
                string path = Server.MapPath("~/Templates/CustomerContactUsMail.html");

                StreamReader str = new StreamReader(path);
                string MailText = str.ReadToEnd();
                str.Close();

                //Repalce [newusername] = signup user name   
                MailText = MailText.Replace("[newusername]", c.CustomerEmail);



                string subject = "Thankyou for Contacting";
                MailMessage _mailmsg = new MailMessage();

                //Make TRUE because our body text is html  
                _mailmsg.IsBodyHtml = true;

                //Set From Email ID  
                _mailmsg.From = new MailAddress(emailSender);

                //Set To Email ID  
                _mailmsg.To.Add(c.CustomerEmail);

                //Set Subject  
                _mailmsg.Subject = subject;

                //Set Body Text of Email   
                _mailmsg.Body = MailText;


                //Now set your SMTP   
                SmtpClient _smtp = new SmtpClient();

                //Set HOST server SMTP detail  
                _smtp.Host = emailSenderHost;

                //Set PORT number of SMTP  
                _smtp.Port = emailSenderPort;

                //Set SSL --> True / False  
                _smtp.EnableSsl = emailIsSSL;

                //Set Sender UserEmailID, Password  
                NetworkCredential _network = new NetworkCredential(emailSender, emailSenderPassword);
                _smtp.Credentials = _network;

                //Send Method will send your MailMessage create above.  
                _smtp.Send(_mailmsg);
                //return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message("Sorry we are facing Problem here" + ex);

            }
        }

        private void sendMailToCompany(ContactUsViewModel contactusViewModel)
        {
            try
            {

                string emailSender = ConfigurationManager.AppSettings["emailsender"].ToString();
                string emailSenderPassword = ConfigurationManager.AppSettings["password"].ToString();
                string emailSenderHost = ConfigurationManager.AppSettings["smtp"].ToString();
                int emailSenderPort = Convert.ToInt16(ConfigurationManager.AppSettings["portnumber"]);
                Boolean emailIsSSL = Convert.ToBoolean(ConfigurationManager.AppSettings["IsSSL"]);
                //string filePath = "~/Templates/SignUpMail.html";
                string path = Server.MapPath("~/Templates/ContactUsMail.html");

                StreamReader str = new StreamReader(path);
                string MailText = str.ReadToEnd();
                str.Close();

                //Repalce [newusername] = signup user name   
                MailText = MailText.Replace("[FirstName]", contactusViewModel.CustomerFirstName).Replace("[LastName]", contactusViewModel.CustomerLastName)
                .Replace("[username]", contactusViewModel.CustomerEmail).Replace("[cardNo]", contactusViewModel.CustomerCardNo).Replace("[comment]", contactusViewModel.Comment);



                string subject = " Customer Contact Mail";
                MailMessage _mailmsg = new MailMessage();

                //Make TRUE because our body text is html  
                _mailmsg.IsBodyHtml = true;

                //Set From Email ID  
                _mailmsg.From = new MailAddress(emailSender);

                //Set To Email ID  
                _mailmsg.To.Add(emailSender);

                //Set Subject  
                _mailmsg.Subject = subject;

                //Set Body Text of Email   
                _mailmsg.Body = MailText;


                //Now set your SMTP   
                SmtpClient _smtp = new SmtpClient();

                //Set HOST server SMTP detail  
                _smtp.Host = emailSenderHost;

                //Set PORT number of SMTP  
                _smtp.Port = emailSenderPort;

                //Set SSL --> True / False  
                _smtp.EnableSsl = emailIsSSL;

                //Set Sender UserEmailID, Password  
                NetworkCredential _network = new NetworkCredential(emailSender, emailSenderPassword);
                _smtp.Credentials = _network;

                //Send Method will send your MailMessage create above.  
                _smtp.Send(_mailmsg);
                //return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message("Sorry we are facing Problem here" + ex);

            }

        }
    }


}

LoyaltyProgram/Views/ContactUs/Index.cshtml
@model LoyaltyProgram.ViewModels.ContactUsViewModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-body register-card-body">
        <p class="login-box-msg">
            You Mean alot to us.If you have a question, comment, or just want to get in touch, Please do!
            We'd love the hear from you.
        </p>

        @using (Html.BeginForm("sendMail", "ContactUs", FormMethod.Post, new { id = "contactus" }))
        {
            <div class="input-group mb-3">
                @Html.Kendo().TextBoxFor(_ => _.CustomerFirstName).HtmlAttributes(new { placeholder = "Enter First Name", @class = "form-control", required = "required", validationmessage = "Enter First Name" })

                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-user"></span>
                    </div>
                </div>
                @Html.Kendo().TextBoxFor(_ => _.CustomerLastName).HtmlAttributes(new { placeholder = "Enter Last Name", @class = "form-control", required = "required", validationmessage = "Enter Last Name" })

                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-user"></span>
                    </div>
                </div>
            </div>
            @*<div class="input-group mb-3">
                    @Html.Kendo().TextBoxFor(_ => _.CustomerLastName).HtmlAttributes(new { placeholder = "Enter Last Name", @class = "form-control", required = "required", validationmessage = "Enter Last Name" })
                    <span class="k-invalid-msg" data-for="CustomerLastName"></span>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>

                </div>*@
            <div class="input-group mb-3">
                @Html.Kendo().TextBoxFor(_ => _.CustomerPhoneNumber).HtmlAttributes(new { placeholder = "Enter Phone Number", @class = "form-control", pattern = "\\d{10}", required = "required", type = "tel", validationmessage = "Enter at least ten digits" })

                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-phone"></span>
                    </div>
                </div>
            </div>
            <div class="input-group mb-3">
                @Html.Kendo().TextBoxFor(_ => _.CustomerEmail).HtmlAttributes(new { placeholder = "e.g. myname@example.net", required = "required", type = "email", data_email_msg = "Email format is not valid", @class = "form-control" })

                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-envelope"></span>
                    </div>
                </div>
            </div>
            <div class="input-group mb-3">
                @Html.Kendo().TextBoxFor(_ => _.CustomerCardNo).HtmlAttributes(new { placeholder = "Enter Loyalty Card Number", required = "required", validationmessage = "Enter Loyalty Card Number", @class = "form-control" })

                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-credit-card"></span>
                    </div>
                </div>
            </div>
            <div class="input-group mb-3">
                @Html.Kendo().TextBoxFor(_ => _.Comment).HtmlAttributes(new { rows =2, cols = 35, placeholder = "Comment", required = "required", data_email_msg = "Comment Required", @class = "form-control" })
                @*@Html.TextAreaFor(_=>_.Comment,new { @class=" form-control k-textbox" , required ="required"})*@
                <div class="input-group-append">
                    <div class="input-group-text">
                        <span class="fas fa-comment"></span>
                    </div>
                </div>
            </div>

            <div class="input-group mb-3">
                <div class="col-4">
                    <button id="btnSubmit" type="submit" class="btn btn-primary btn-block">Submit</button>

                </div>
            </div>

        }
    </div>
</div>